config/routes.rb
Rails.application.routes.draw do
  resources :post_reviews
  resources :products
  resources :master_categories


  devise_for :users, controllers: {
        sessions: 'users/sessions',
        registrations:'users/registrations'

      }

        get "user_profile" =>"products#user_profile", as: :user_profile	
        post "add_reply" =>"post_reviews#add_reply", as: :add_reply

        root 'products#index'

      #devise_for :users, registerations: 'users/registerations'
  #resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/post_reviews_controller.rb
class PostReviewsController < ApplicationController
  before_action :set_post_review, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: %i[show]

  # GET /post_reviews
  # GET /post_reviews.json
  def index
    @post_reviews = PostReview.all
  end

  # GET /post_reviews/1
  # GET /post_reviews/1.json
  def show
  end

  # GET /post_reviews/new
  def new
    @post_review = PostReview.new
  end

  # GET /post_reviews/1/edit
  def edit
  end

  # POST /post_reviews
  # POST /post_reviews.json
  def create
    @post_review = PostReview.new(post_review_params)

    respond_to do |format|
      if @post_review.save
        format.html { redirect_to product_path(@post_review.product_id), notice: ' ThankYou for your reviews.' }
        format.json { render :show, status: :created, location: @post_review }
      else
        format.html { render :new }
        format.json { render json: @post_review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /post_reviews/1
  # PATCH/PUT /post_reviews/1.json
  def update
    respond_to do |format|
      if @post_review.update(post_review_params)
        format.html { redirect_to @post_review, notice: 'Post review was successfully updated.' }
        format.json { render :show, status: :ok, location: @post_review }
      else
        format.html { render :edit }
        format.json { render json: @post_review.errors, status: :unprocessable_entity }
      end
    end
  end

  def add_reply

  commentuser_id = PostReview.find_by_id(params[:review_id])
  @reply_comment = ReplyReview.new
  @reply_comment.post_review_id = params[:review_id]
  @reply_comment.user_id = current_user.id
  @reply_comment.message = params[:reply_msg]
  @reply_comment.save
  flash[:notice] = 'Comment added successfully. '
  redirect_to product_path(params[:product_id])

end

  # DELETE /post_reviews/1
  # DELETE /post_reviews/1.json
  def destroy
    @post_review.destroy
    respond_to do |format|
      format.html { redirect_to post_reviews_url, notice: 'Post review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post_review
      @post_review = PostReview.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_review_params
      params.require(:post_review).permit(:user_id,:product_id,:rating,:message)
    end
end

app/helpers/post_reviews_helper.rb
module PostReviewsHelper
end

app/views/post_reviews/_form.html.erb
<div class="container">
<div class="row">
<div class="col-md-6 card card-body bg_primry">



<%= form_for(@post_review) do |f| %>
  <% if @post_review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post_review.errors.count, "error") %> prohibited this post_review from being saved:</h2>

      <ul>
        <% @post_review.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

 
     <div class="form-group">
    <label for="rating">User Rating</label><br />
          
          <%= f.radio_button :rating, '1' %>
          <%= f.radio_button :rating, '2' %>
          <%= f.radio_button :rating, '3' %>
          <%= f.radio_button :rating, '4' %>
          <%= f.radio_button :rating, '5' %>

    </div>
    <div class="form-group">
    <label for="MESSAGE">Your Review</label><br />
    
    <%= f.text_area :message, autocomplete: "message", class: "form-control",required: "true" %>
  </div>

    <%= f.hidden_field :user_id, :value=> current_user.id %>
    <% if params[:action] != "edit" %>
    <%= f.hidden_field :product_id, :value=> @product.id %>
    <% end %>
<%= f.submit "Add Review" ,:class => "btn btn-primary" %>
<% end %>
</div>
<div class="col-md-3">
</div>
</div>
</div>

app/views/post_reviews/edit.html.erb
<center><h1>Editing  Review</h1></center>
<div class="container mt-5">
	<div class="col-md-3">
	</div>
<div class="col-md-12">

<%= render 'form', post_review: @post_review %>

</div>
<div class="col-md-3">
	</div>


</div>

app/views/post_reviews/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Post Reviews</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @post_reviews.each do |post_review| %>
      <tr>
        <td><%= link_to 'Show', post_review %></td>
        <td><%= link_to 'Edit', edit_post_review_path(post_review) %></td>
        <td><%= link_to 'Destroy', post_review, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post Review', new_post_review_path %>

app/views/post_reviews/new.html.erb
<h1>New Post Review</h1>

<%= render 'form', post_review: @post_review %>

<%= link_to 'Back', post_reviews_path %>

app/views/post_reviews/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_post_review_path(@post_review) %> |
<%= link_to 'Back', post_reviews_path %>