config/routes.rb
Rails.application.routes.draw do
  resources :post_reviews
  resources :products
  resources :master_categories


  devise_for :users, controllers: {
        sessions: 'users/sessions',
        registrations:'users/registrations'

      }

        get "user_profile" =>"products#user_profile", as: :user_profile	
        post "add_reply" =>"post_reviews#add_reply", as: :add_reply

        root 'products#index'

      #devise_for :users, registerations: 'users/registerations'
  #resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord

	mount_uploader :image, AvatarUploader

	belongs_to :master_category
	belongs_to :user
	has_many :post_reviews

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: %i[index show]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
    #@groupproduct = Product.group(:master_category_id)
    @category = MasterCategory.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @related_products = Product.where.not(id:params[:id])
    @category = MasterCategory.all
    @post_review = PostReview.new
    @product_reviews  = @product.post_reviews
  end

  # GET /products/new
  def new
    @product = Product.new
    @category = MasterCategory.all
  end

  # GET /products/1/edit
  def edit
    @category = MasterCategory.all
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)
    @category = MasterCategory.all
    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end


  def user_profile

    #alluser = User.find_by(id: current_user.id)

    @myproducts = Product.where(user_id: current_user.id)
    #@mtt   = @myreviews.group(:product_id)


    
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
     params.require(:product).permit(:name,:master_category_id,:user_id,:description,:image)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<div class="container" style="margin-top: 10%;">
<div class="row">
<div class="col-md-3">
</div>
<div class="col-md-6 card card-body bg_primry">



<%= form_with(model: product, local: true) do |f| %>
   <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  
  <div class="form-group">
   <label for="exampleInputEmail1">Name</label>
    <%= f.text_field :name, autofocus: true, autocomplete: "name", class: "form-control",required: "true" %>
  </div>

  <div class="form-group">
    <label for="exampleInputEmail1">Description</label><br />
    <%= f.text_field :description, autocomplete: "title", class: "form-control",required: "true" %>
  </div>
  <%= f.hidden_field :user_id, value: current_user.id %>
  <div class="form-group">
    <%= f.label :master_category_id %><br />
    <%= f.collection_select :master_category_id,@category, :id,:name,{ :prompt => 'Select Category' },{ class: "form-control add_city", :required => true} %>
  </div>
   <div class="form-group">
    <%= f.label :image %><br />
    <%= f.file_field :image, autocomplete: "image", class: "form-control",required: "true" %>
  </div>


<div class="row">
  <div class="col-md-6">
      
        <%= f.submit "Add Product" ,:class => "btn btn-primary" %>
      
  </div>
  
</div>
<% end %>

<%#= render "devise/shared/links" %>

</div>
<div class="col-md-3">
</div>
</div>
</div>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<%# Product.order(created_at: :asc).group_by(&:master_category_id).each do |vv, index| %>
<%#= "#{index}" %>
<%# end %>
<div class="container">

  <h1 class="font-weight-light text-center mt-4 mb-0">Product Gallery</h1>

  <hr class="mt-2 mb-5">

  <div class="row text-center text-lg-left">
<% @products.each do |product| %>
    <div class="col-lg-3 col-md-4 col-6 product_gallery mb-5">
<b><p> <%= product.name %></p></b>
      <%= link_to product,:class=> "d-block mb-3" do %>
  <%= image_tag(product.image.url,:class=> "img-fluid img-thumbnail") %>
<% end %>
<p><%= product.description.truncate_words(20) %></p>
      
    </div>
    <% end %>
    
  </div>

</div>
<!-- /.container -->

app/views/products/new.html.erb
<center><h1>New Product</h1></center>

<%= render 'form', product: @product %>

<%#= link_to 'Back', products_path %>

app/views/products/show.html.erb
<!-- Page Content -->
<div class="container">

  <!-- Portfolio Item Heading -->
  <h1 class="my-4"><%= @product.name %></h1>

  <!-- Portfolio Item Row -->
  <div class="row">

    <div class="col-md-6">
    	<%= image_tag @product.image.url,:class=> "img-fluid show_product_image" %>
    	<p class="mt-2"><i class="fa fa-tag" aria-hidden="true"></i> <span><%= @product.master_category.name.capitalize%></span> <span><i class="fa fa-user-circle-o" aria-hidden="true"></i> <%= @product.user.name.capitalize %></span></p>
      
    </div>

    <div class="col-md-6">
      <h3 class="my-3"> Description</h3>
      <p><%= @product.description %></p>
     <h4>Reviews</h4>
     <% @product_reviews.each do |vv| %>
     <div class="card_data">
     <span><i class="fa fa-user-circle-o" aria-hidden="true"></i> <%= vv.user.name %></span><br>
     <% (1..5).each do |gg| %>
     <%=  @disable = vv.rating.to_i >= gg ? '<i class="fa fa-star rating_star" aria-hidden="true"></i>'.html_safe : '<i class="fa fa-star-o" aria-hidden="true"></i>'.html_safe
 %>
     <%# @reviewselected = @disable == true ? false : true %>
     
     <%#= radio_button_tag (vv.id.to_s+"pro".to_s+gg.to_s),'available', vv.rating.to_i >= gg, :disabled=> @reviewselected  %>
     <% end %><br>

 
     <%= vv.message %>  <span class="pl-5 link"><%= user_signed_in? ? current_user.id == vv.user_id ? (link_to "(Edit)", edit_post_review_path(vv.id)) : "" : "" %></span>
     </div></br>
     <% if vv.reply_reviews.present? %>
    <%  vv.reply_reviews.each do |ss| %>

    <span><i class="fa fa-user-circle-o" aria-hidden="true"></i> <%= ss.user.name %></span><br>
    <%= ss.message %></br>


    <% end %>

     <% end %> <br/>
     <% if user_signed_in? %>

 

<form class="form-inline" method="POST" id ="formreply-button<%= vv.id %>" >
  <div class="form-row align-items-center">
    <div class="col-auto">
     
      <textarea class="form-control" name="reply_message" id="exampleFormControlTextarea1" cols="28" rows="2"></textarea>
     
    </div>
      <input type="hidden" id="article_id" name="article_id" value= <%= vv.id %> >
    
    <%#= text_area :message, class: "form-control", placeholder: "Your Comment" , required: 'true' %>
    

  
   <div class="col-auto">
      <button type="button" id="reply-button<%= vv.id %>" onclick="replycomment(this.id)" class="btn btn-primary mb-2">Reply</button>
    </div>
    </div>
</form>
<% end %>
 </br>
     <% end %>
    </div>

  </div>
  <!-- /.row -->
  <div class="container">

  <h1 class="my-4">Post a Review</h1>

  <% if current_user %>

<%= render "post_reviews/form" %>
<% else %>
<div class="container">
<div class="row">
<div class="col-md-6 card card-body bg_primry">
<center><h5>Please Login/Signup to Review  Product</h5></center>
<div class="mt-4 text-center">
<span><%= link_to "Log in", new_user_session_path,:class => "btn btn-info btn-xs btn_width" %></span>
<span><%= link_to "Sign up", new_user_registration_path,:class => "btn btn-danger btn-xs btn_width" %></span>
</div>
</div>
</div>
</div>
<% end %>
</div>
<hr>

  <!-- Related Projects Row -->
  <h3 class="my-4">Related Projects</h3>

  <div class="row related">
  	<% @related_products.each do |cc| %> 

    <div class="col-md-3 col-sm-6 mb-4">

<%= link_to cc,:class=> "d-block mb-3" do %>
  <%= image_tag(cc.image.url,:class=> "img-fluid img-thumbnail") %>
<% end %>

      
    </div>

    <% end %>

  </div>
  <!-- /.row -->

</div>
<!-- /.container -->
<script type="text/javascript">


function replycomment(clicked_id) {
	var form_id = "form"+clicked_id;
	//alert(form_id);
	var comment_id = document.getElementById(form_id).elements.namedItem("article_id").value;
	var reply_msg = document.getElementById(form_id).elements.namedItem("reply_message").value;
	var product_id = '<%=params[:id]%>';
	//alert(product_id);
	//var elem2 = elem1.closest("#article_id");
   $.ajax({
              beforeSend: function(xhr) {xhr.setRequestHeader('X-CSRF-Token', $('meta[name="csrf-token"]').attr('content'))},
              type:'post',
              async: true,

              url: '/add_reply',
              data: {review_id: comment_id, reply_msg: reply_msg,product_id: product_id}


            });
 // var formid = document.getElementById("demo");
}


$(document).ready(function(){
  $("#reply-button").click(function(){
    alert("The paragraph was clicked.");
  


	
});
});
</script>

app/views/products/user_profile.html.erb
<div class="container">
   <center><h2>User Profile</h2></center>

<div class="card">
<% if current_user.image.present? %>
  <%=  image_tag current_user.image.url,:class =>"img_width"  %>

  <% else %>
 <%=  image_tag "/assets/nnnn.jpg",:class =>"img_width"  %>
  <% end %>
  <h3 class="mt-3"><%= current_user.name.capitalize %></h3>
  <p class="title"><%= current_user.email %></p>
  
  <div style="margin: 24px 0;">
    <a href="#"><i class="fa fa-dribbble"></i></a> 
    <a href="#"><i class="fa fa-twitter"></i></a>  
    <a href="#"><i class="fa fa-linkedin"></i></a>  
    <a href="#"><i class="fa fa-facebook"></i></a> 
  </div>
  <p><%= link_to 'Edit Profile', "/users/edit", class: "edit_profile"%></p>
</div>
</div>


<div class="container">

  <h1 class="font-weight-light text-center mt-4 mb-0">My  Products</h1>

  <hr class="mt-2 mb-5">

  <div class="row text-center text-lg-left">
<% @myproducts.each do |product| %>
    <div class="col-lg-3 col-md-4 col-6 product_gallery mb-5">
<b><p> <%= product.name %></p></b>
      <%= link_to product,:class=> "d-block mb-3" do %>
  <%= image_tag(product.image.url,:class=> "img-fluid img-thumbnail") %>
<% end %>
<p><%= product.description.truncate_words(20) %></p>
      
    </div>
    <% end %>
    
  </div>

</div>


<style>
.card {
  box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
  max-width: 300px;
  margin: auto;
  text-align: center;
  font-family: arial;
}

.title {
  color: grey;
  font-size: 15px;
}

.edit_profile {
  border: none;
  outline: 0;
  display: inline-block;
  padding: 8px;
  color: white;
  background-color: #000;
  text-align: center;
  cursor: pointer;
  width: 100%;
  font-size: 18px;
}

a {
  text-decoration: none;
  font-size: 18px;
  color: black;
}

.edit_profile:hover, a:hover {
  opacity: 0.7;
}
</style>